config/routes.rb
Rails.application.routes.draw do
  resources :ankits
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ankit.rb
class Ankit < ApplicationRecord
    validates :name, presence: true, format: {with: /\A[a-zA-Z]+\Z/, massage: 'only latter are allowed'}
    validates :age, presence: true, length: {minimum:1, maximum:2}, numericality: true
    validates :email, presence: true, uniqueness: true
    before_create :greeting_masssage
    def greeting_masssage
      puts" hey!" 
    end
    
    before_save :update_ankit_name

    def update_ankit_name
        self.name.downcase!
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/ankits_controller.rb
class AnkitsController < ApplicationController  
  before_action :set_ankit, only: %i[ show edit update destroy ]
  before_action :print_massage
  after_action :print_this

  def print_massage
     puts "i am ankit"
  end
  def print_this
    puts "======================================="
   puts "okk bye"
   puts "======================================="

  end

  # GET /ankits or /ankits.json
  def index
    @ankits = Ankit.all
  end

  # GET /ankits/1 or /ankits/1.json
  def show
  end

  # GET /ankits/new
  def new
    @ankit = Ankit.new
  end

  # GET /ankits/1/edit
  def edit
  end

  # POST /ankits or /ankits.json
  def create
    @ankit = Ankit.new(ankit_params)

    respond_to do |format|
      if @ankit.save
        CrudNotificationMailer.create_notification(@ankit).deliver_now
        format.html { redirect_to ankit_url(@ankit), notice: "Ankit was successfully created." }
        format.json { render :show, status: :created, location: @ankit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ankit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ankits/1 or /ankits/1.json
  def update
    respond_to do |format|
      if @ankit.update(ankit_params)
        CrudNotificationMailer.update_notification(@ankit).deliver_now
        format.html { redirect_to ankit_url(@ankit), notice: "Ankit was successfully updated." }
        format.json { render :show, status: :ok, location: @ankit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ankit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ankits/1 or /ankits/1.json
  def destroy
    CrudNotificationMailer.delete_notification(@ankit).deliver_now
    @ankit.destroy

    respond_to do |format|
      format.html { redirect_to ankits_url, notice: "Ankit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ankit
      @ankit = Ankit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ankit_params
      params.require(:ankit).permit(:name, :email, :age)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/ankits_helper.rb
module AnkitsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ankits/_form.html.erb
<%= form_with(model: ankit, local: true) do |form| %>
  <% if ankit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ankit.errors.count, "error") %> prohibited this ankit from being saved:</h2>

      <ul>
        <% ankit.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.text_field :age %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ankits/edit.html.erb
<h1>Editing Ankit</h1>

<%= render 'form', ankit: @ankit %>

<%= link_to 'Show', @ankit %> |
<%= link_to 'Back', ankits_path %>

app/views/ankits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ankits</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ankits.each do |ankit| %>
      <tr>
        <td><%= ankit.name %></td>
        <td><%= ankit.email %></td>
        <td><%= ankit.age %></td>
        <td><%= link_to 'Show', ankit %></td>
        <td><%= link_to 'Edit', edit_ankit_path(ankit) %></td>
        <td><%= link_to 'Destroy', ankit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ankit', new_ankit_path %>

app/views/ankits/new.html.erb
<h1>New Ankit</h1>

<%= render 'form', ankit: @ankit %>

<%= link_to 'Back', ankits_path %>

app/views/ankits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ankit.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @ankit.email %>
</p>

<p>
  <strong>Age:</strong>
  <%= @ankit.age %>
</p>

<%= link_to 'Edit', edit_ankit_path(@ankit) %> |
<%= link_to 'Back', ankits_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>